version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: dev_wpmu
    depends_on:
      - db
    ports:
      - 80:80
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${ROOT_USERNAME}
      WORDPRESS_DB_PASSWORD: ${ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${NETWORK}
#mount volume localhost with docker container. Share file from container to local
    volumes:
     - ./html:/var/www/html

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: dev_wpmu_db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${NETWORK}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
     - ./DB:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge-4.8
    container_name: dev_wpmu_phpmyadmin
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      PMA_HOST: db
    ports:
     - 8080:80
