version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: dev_wpmu
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
#mount volume localhost with docker container. Share file from container to local
    volumes:
     - ./html:/var/www/html

  db:
    image: mysql:5.7
    container_name: dev_wpmu_db
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
     - ./DB:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge-4.8
    container_name: dev_wpmu_phpmyadmin
    restart: always
    environment:
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      PMA_HOST: db
    ports:
     - 8080:80
